name: Build pdf
on: 
  push:
    paths:
      - '.github/**'
      - 'src/**'
jobs:
  build_pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate PDF
        uses: fifsky/html-to-pdf-action@master
        with:
          htmlFile: src/index.html
          outputFile: src/resume.pdf
          pdfOptions: '{"format": "A2", "margin": {"top": "0", "left": "0", "right": "0", "bottom": "0"}}'
      - name: Upload resume
        uses: actions/upload-artifact@v4
        with:
          name: resume
          path: src/resume.pdf